version: '3.8'

services:
  app:
    container_name: rtsp_hls_converter
    restart: always
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
